In [24]:
import numpy as np

A = np.array([[2,3,2], [10, 3,4],[3,6,1]])
x = np.zeros([A.shape[0],1])
x[-1] = 1

np.linalg.eig(A)

# A = np.array([[3,1], [1, 3]])
# x = np.zeros([A.shape[0],1])
# x[-1] = 1

ratio = 0

for k in range(1, 10):
    
    # generate next vector
    x = A.dot(x)
    print(x.T)
    ratio = 3 + x[0]/x[1]
    print('ratio:', ratio)


[[2. 4. 1.]]
ratio: [3.5]
[[18. 36. 31.]]
ratio: [3.5]
[[206. 412. 301.]]
ratio: [3.5]
[[2250. 4500. 3391.]]
ratio: [3.5]
[[24782. 49564. 37141.]]
ratio: [3.5]
[[272538. 545076. 408871.]]
ratio: [3.5]
[[2998046. 5996092. 4496941.]]
ratio: [3.5]
[[32978250. 65956500. 49467631.]]
ratio: [3.5]
[[3.62761262e+08 7.25522524e+08 5.44141381e+08]]
ratio: [3.5]


In [25]:
A = np.array([[6,2,1], [2,3,1],[1,1,1]])
x = np.zeros([A.shape[0],1])
x[-1] = 1

np.linalg.eig(A)

(array([7.28799214, 2.13307448, 0.57893339]),
 array([[ 0.86643225,  0.49742503, -0.0431682 ],
        [ 0.45305757, -0.8195891 , -0.35073145],
        [ 0.20984279, -0.28432735,  0.9354806 ]]))