Please **submit this Jupyter notebook through Canvas** no later than **Monday November 12, 12:59**, before the start of the lecture.

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

**Jordan Earle** (12297127)

**Natasja Wezel** (11027649)

-----
# Exercise 1

## (a)
Let $A$ be the matrix $\begin{bmatrix} 1 & -1 & \alpha \\ 2 & 2 & 1 \\ 0 & \alpha & -3/2 \end{bmatrix}$. For which values of $\alpha$ is $A$ singular?

In [11]:
import numpy as np
import scipy as sp
from scipy import linalg as la
from sympy import *
from sympy import Matrix
x = Symbol('x')
matA = Matrix([[1, -1, x], [2, 2, 1], [0, x, -3/2]])

print(matA)

print(matA.det())
equation = matA.det()
solutions = solve(equation)

print("The values where alpha is zero are:", solutions[0],solutions[1])

Matrix([[1, -1, x], [2, 2, 1], [0, x, -1.50000000000000]])
2*x**2 - x - 6.0
The values where alpha is zero are: -1.50000000000000 2.00000000000000


## (b)
Consider the following linear system of equations:
$$
\begin{align*}
2x + y + z & = 3 \\
2x - y + 3z &= 5 \\
-2x + \alpha y + 3z &= 1.
\end{align*}
$$
For what values of $\alpha$ does this system have an infinite number of solutions?

In [3]:
a = Symbol('a')

matB = Matrix([[2, 1, 1], [2, -2, 3], [-2, a, 3]])

print(matB.det())
equation = matB.det()
solutions = solve(equation)

print("The values where alpha causes the system to be singular and therefore infinitly many solutions are: ", solutions[0])

-4*a - 28
The values where alpha causes the system to be singular and therefore infinitly many solutions are:  -7


## (c)
Denote the columns of an $n \times n$ matrix $A$ as $A_k$ for $k=1,\ldots,n$. We define the function $||A||_* = \max_k ||A_k||_2$. Show that $||A||_*$ is a norm, in that it satisfies the first three properties of a matrix norm (cf. §2.3.2).

----
# Exercise 2
For solving linear systems such as $Ax = b$, it is unnecessary (and often unstable) to compute the inverse $A^{-1}$. Nonetheless, there can be situations where it is useful to compute $A^{-1}$ explicitly. One way to do so is by using the LU-decomposition of $A$.

## (a)
Write an algorithm to compute $A^{-1}$ for a non-singular matrix $A$ using its LU-decomposition. You can use `scipy.linalg.lu` (which returns an LU-decomposition with _partial pivoting_, i.e., with a permutation matrix $P$) and the other `scipy.linalg.lu_*` functions, but not `scipy.linalg.inv` (or other methods for computing matrix inverses directly).

In [38]:
def solveInverse(matA):
    
    shapeA = matA.shape
    validity = True
    p, l, u = sp.linalg.lu(newMatA)
    
    for i in range(0,shapeA[0]):
        if l[i][i] == 0 or u[i][i] == 0:
            validity = False
            
    if validity == False:
        print("This does not work dude!")
        break
        
    pt = p.transpose()
    b = forwardSublower(shape, lw, pt)

def forwardSublower(s,lw,pt):
    tmpMat = np.empty(shape = s)
    for i in range(0, s[0]):
        tmpCell = 0
        if lw[i][i] == 0:
            print("This is an invalid matrix.  Breaking this beast.")
            break
            for j in range(0, s[1]):
                tmpCell = tmpCell + (pt[i][j]/lw[i][j])
                matrixInv[i][j] = tmpCell
    return tmpMat

def backwardSubsolver(s, up, b):

    tmpMat = np.empty(shape = s)
    for i in range(0, s[0], -1):
        tmpCell = 0
        if lw[i][i] == 0:
            print("This is an invalid matrix.  Breaking this beast.")
            break
            for j in range(0, s[1]):
                tmpCell = tmpCell + (pt[i][j]/lw[i][j])
                matrixInv[i][j] = tmpCell
    return tmpMat

    
newMatA = np.array([[1, -1, 1], [2,2,1], [0, 1, -3/2]])

print(sp.linalg.inv(newMatA))
#print(p)
print(l)
print(u)

pt = p.transpose()

print(pt.dot(sp.linalg.inv(l)))



[[ 0.8  0.1  0.6]
 [-0.6  0.3 -0.2]
 [-0.4  0.2 -0.8]]
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.  -0.5  1. ]]
[[ 2.    2.    1.  ]
 [ 0.   -2.    0.5 ]
 [ 0.    0.   -1.25]]
[[-0.5   1.    0.  ]
 [ 1.    0.    0.  ]
 [-0.25  0.5   1.  ]]


## (b)
What is the computational complexity of your algorithm, given that the input matrix has size $n \times n$?

## (c)
Apply your Python code to compute the inverse of the Hilbert matrix $H_n$ for $n=1, \ldots, 12$ (see https://en.wikipedia.org/wiki/Hilbert_matrix) -- you can use `scipy.linalg.hilbert`. This matrix is _very_ ill-conditioned, so computing its inverse is very hard for large $n$.

Compare the inverse with the "true" inverse given by `scipy.linalg.invhilbert`. Output a (`plt.semilogy`) graph showing how the $\infty$-norm of their difference progresses for $n$.

## (d)
It is known that the $2$-condition number $cond_2(H_n)$ of the Hilbert matrix grows like $\mathcal O\left(\frac{(1+\sqrt{2})^{4n}}{\sqrt{n}}\right)$. Does the $\infty$-condition number (defined in Example 2.5) of $H_n$ grow in a similar way?
For the matrix inverse, try both your own matrix inversion routine, and `scipy.linalg.invhilbert`. Output a (`plt.semilogy`) graph showing your results.