Please **submit this Jupyter notebook through Canvas** no later than **Monday November 12, 12:59**, before the start of the lecture.

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

**Jordan Earle** (12297127)

**Natasja Wezel** (11027649)

-----
# Exercise 1

## (a)
Let $A$ be the matrix $\begin{bmatrix} 1 & -1 & \alpha \\ 2 & 2 & 1 \\ 0 & \alpha & -3/2 \end{bmatrix}$. For which values of $\alpha$ is $A$ singular?

In [1]:
import numpy as np
import scipy as sp
from scipy import linalg as la
from sympy import *
from sympy import Matrix
x = Symbol('x')
matA = Matrix([[1, -1, x], [2, 2, 1], [0, x, -3/2]])

print(matA)

print(matA.det())
equation = matA.det()
solutions = solve(equation)

print("The values where alpha is zero are:", solutions[0],solutions[1])

Matrix([[1, -1, x], [2, 2, 1], [0, x, -1.50000000000000]])
2*x**2 - x - 6.0
The values where alpha is zero are: -1.50000000000000 2.00000000000000


## (b)
Consider the following linear system of equations:
$$
\begin{align*}
2x + y + z & = 3 \\
2x - y + 3z &= 5 \\
-2x + \alpha y + 3z &= 1.
\end{align*}
$$
For what values of $\alpha$ does this system have an infinite number of solutions?

In [2]:
a = Symbol('a')

matB = Matrix([[2, 1, 1], [2, -2, 3], [-2, a, 3]])

print(matB.det())
equation = matB.det()
solutions = solve(equation)

print("The values where alpha causes the system to be singular and therefore infinitly many solutions are: ", solutions[0])

-4*a - 28
The values where alpha causes the system to be singular and therefore infinitly many solutions are:  -7


## (c)
Denote the columns of an $n \times n$ matrix $A$ as $A_k$ for $k=1,\ldots,n$. We define the function $||A||_* = \max_k ||A_k||_2$. Show that $||A||_*$ is a norm, in that it satisfies the first three properties of a matrix norm (cf. §2.3.2).

The first three properties of a matrix norm, where A and B are any matrices, are:
1. Positivity:

||A|| > 0 if A $\neq$ $\textbf{O}$

2. Homogeneity:

||$\lambda \textbf{A} $|| = $|\lambda| \cdot || \textbf{A} ||$ for any scalar $\lambda$

3. Triangle inequality:

$||\textbf{A} + \textbf{B}|| \leq  || \textbf{A} || + || \textbf{B} ||$

Note that the first two properties together imply that $||A|| = 0$ if, and only if, $A = 0$.

For all proves the fact that $max_k ||A_k||_2$ is a norm is used.

$$ % TODO: I'm not sure how to properly write this $$

1.To prove that $||A||_*$ is positive

$$
\begin{align}
    max_{1 \leq k \leq n} || A_k ||_2 > 0
\end{align}
$$
$ $

$\exists k : || A_k ||_2 > 0 $, so: $A_k \neq 0 => A \neq 0$

This proves that the first part:
$||A||_*$ > if $A \neq O$

2. To prove the second property:

$$
\begin{align*}
    || \lambda A ||_* &= max_k ||\lambda A_k||_2\\
                      &= max_k (|\lambda | \cdot ||A_k||_2)\\
                      &= |\lambda| \cdot max_k ||A_k||_2\\
                      &= |\lambda| \cdot ||A||_*
\end{align*}
$$

3. To prove the third property:

$$
\begin{align*}
    || A + B ||_* = max_k || A_k + B_k||_2 &\leq max_k (||A_k||_2 + ||A_k||_2) \\ 
                      &\leq max_k ||A_k|| + max_l ||B_l|| \\
                      &\leq ||A||_* + ||B||_*|
\end{align*}
$$
 

----
# Exercise 2
For solving linear systems such as $Ax = b$, it is unnecessary (and often unstable) to compute the inverse $A^{-1}$. Nonetheless, there can be situations where it is useful to compute $A^{-1}$ explicitly. One way to do so is by using the LU-decomposition of $A$.

## (a)
Write an algorithm to compute $A^{-1}$ for a non-singular matrix $A$ using its LU-decomposition. You can use `scipy.linalg.lu` (which returns an LU-decomposition with _partial pivoting_, i.e., with a permutation matrix $P$) and the other `scipy.linalg.lu_*` functions, but not `scipy.linalg.inv` (or other methods for computing matrix inverses directly).

In [41]:
import numpy as np

def solveInverse(matA):
    
    shapeA = matA.shape
    validity = True
    p, l, u = sp.linalg.lu(matA)
    
    print(p)
    print(l)
    print(u)
    print(p.dot(l.dot(u)))
    
    for i in range(0,shapeA[0]):
        if l[i][i] == 0 or u[i][i] == 0:
            print("Matrix is not invertable!")
            return False, np.empty(shape = s)
        
    b = p.transpose().dot(np.eye(3, dtype=float))
    c = forwardSublower(shapeA, l, b)
    inverted = backwardSubsolver(shapeA, u, c)
    
    return True, inverted

def forwardSublower(s,lw,pt):
    tmpMat = np.empty(shape = s)
    for n in range(0, s[1]): # cycle through columns
        for m in range(0, s[0]): # cycle through rows
            tmpMat[m][n] = (pt[m][n]/lw[m][m]) # Find current X val 
            for i in range(m+1, s[1]): # Subtract that value from all other colutions
                pt[i][n] = pt[i][n] - (pt[i][n]*tmpMat[m][n])
    return tmpMat

def backwardSubsolver(s, up, tmpA):
    tmpMat = np.empty(shape = s)
    for n in range(s[0]-1, -1, -1):#starting at the last column, go through the columns
        for m in range(s[1]-1, -1, -1): # starting at the last row, go through the rows.
            tmpMat[m][n] = (b[m][n]/up[m][m]) # Find current X val 
            for i in range(0, m-1): # Subtract that value from all other colutions
                 tmpA[i][n] = tmpA[i][n] - (tmpA[i][n]*tmpMat[m][n])
    return tmpMat

    
MatA = np.array([[5., 7., 12.], [13.,14.,2.], [11., 15., 10]])
print(MatA)

check, inverted = solveInverse(MatA)
if check:
    print(b)
    print(sp.linalg.inv(newMatA))

[[ 5.  7. 12.]
 [13. 14.  2.]
 [11. 15. 10.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.84615385 1.         0.        ]
 [0.38461538 0.51219512 1.        ]]
[[13.         14.          2.        ]
 [ 0.          3.15384615  8.30769231]
 [ 0.          0.          6.97560976]]
[[ 5.  7. 12.]
 [13. 14.  2.]
 [11. 15. 10.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[ 0.38461538  0.38461538 -0.53846154]
 [-0.37762238 -0.28671329  0.51048951]
 [ 0.14335664  0.00699301 -0.07342657]]


In [6]:
newMatA = np.array([[1, -1, 1], [2,2,1], [0, 1, -3/2]])

p, l, u = sp.linalg.lu(newMatA)
print(p)
print(l)
print(u)

Ainv = sp.linalg.inv(newMatA)

Ident = newMatA.dot(Ainv)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.  -0.5  1. ]]
[[ 2.    2.    1.  ]
 [ 0.   -2.    0.5 ]
 [ 0.    0.   -1.25]]


## (b)
What is the computational complexity of your algorithm, given that the input matrix has size $n \times n$?

It will have a computational complexity of $n^{3}/3$

## (c)
Apply your Python code to compute the inverse of the Hilbert matrix $H_n$ for $n=1, \ldots, 12$ (see https://en.wikipedia.org/wiki/Hilbert_matrix) -- you can use `scipy.linalg.hilbert`. This matrix is _very_ ill-conditioned, so computing its inverse is very hard for large $n$.

Compare the inverse with the "true" inverse given by `scipy.linalg.invhilbert`. Output a (`plt.semilogy`) graph showing how the $\infty$-norm of their difference progresses for $n$.

In [ ]:
import scipy as sp
from scipy import linalg as la

for n in range(12):
    # get the Hilbert matrix
    Hn = la.hilbert(n + 1)
    
    check, inverted = solveInverse(MatA)
    
    # compare to the true inverse
    true_inverse_Hn = la.invhilbert(n + 1)
    
    # so we do || true_inverse - own_inverse || infinity norm
    
    infinNorm = max(abs(true_inverse_Hn - inverted))
    

## (d)
It is known that the $2$-condition number $cond_2(H_n)$ of the Hilbert matrix grows like $\mathcal O\left(\frac{(1+\sqrt{2})^{4n}}{\sqrt{n}}\right)$. Does the $\infty$-condition number (defined in Example 2.5) of $H_n$ grow in a similar way?
For the matrix inverse, try both your own matrix inversion routine, and `scipy.linalg.invhilbert`. Output a (`plt.semilogy`) graph showing your results.