Please **submit this Jupyter notebook through Canvas** no later than **Monday November 19, 12:59**, before the start of the lecture.

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

-------------
# Exercise 1
# (a)
Let $Q$ be a real, square orthogonal matrix. Show that all eigenvalues of $Q$ satisfy $|\lambda |=1$.


# (b)
A projection matrix is a matrix $P$ for which $P^2=P$. Find the eigenvalues of a projection matrix.

-----------
# Exercise 2
Generate a symmetric $4 × 4$ matrix $A$ randomly, e.g. as below.
Implement Rayleigh quotient iteration (Algorithm 4.4) to compute the largest eigenvalue and corresponding eigenvector of $A$. Use a suitable stopping criterion for your iterations (and explain why you think it is suitable). You may use `scipy.linalg.solve`.

In [1]:
import numpy as np
import scipy.linalg
B = np.random.randn(4,4)
A = B+B.T

In [3]:
print(A)

[[ 1.21280794  1.53687928  1.2428759   3.19395717]
 [ 1.53687928 -1.46403765  0.01709223 -2.18411377]
 [ 1.2428759   0.01709223 -1.7035636   0.76089606]
 [ 3.19395717 -2.18411377  0.76089606 -2.42354654]]


In [2]:
A = [[3, 1], [1, 3]]

In [5]:
# def Ray_Quotient(matrix, iterations):

In [45]:
matrix = np.array(A)
iterations = 3

In [64]:
# x = np.transpose([0,1])

A = np.array([[3.,1.], [1., 3.]])
I = np.eye(A.shape[0])

# print(x)
print(A)

x = np.zeros([matrix.shape[0],1])

x[-1] = 1.0
print(x)

for k in range(1, iterations):
    print("iteratie: ", k)
    xT = x.T
    print('xT', xT)

    # compute shift
    sigma = ((xT.dot(A)).dot(x)) / (xT.dot(x))
    print('s',sigma)
    
    # generate next vector
    thingy = (A - sigma * I)
    
    y = np.linalg.solve(thingy, x)
    print('y',y)
    
    # normalize (update x)
    x = y / np.linalg.norm(y, ord = np.inf)
    
    print('x', x) 
    print('inf y', np.linalg.norm(y, np.inf))

[[3. 1.]
 [1. 3.]]
[[0.]
 [1.]]
iteratie:  1
xT [[0. 1.]]
s [[3.]]
y [[1.]
 [0.]]
x [[1.]
 [0.]]
inf y 1.0
iteratie:  2
xT [[1. 0.]]
s [[3.]]
y [[0.]
 [1.]]
x [[0.]
 [1.]]
inf y 1.0


In [19]:
x

array([1., 1.])

In [16]:
sigma

array([[3., 1.],
       [1., 3.]])

In [10]:
np.linalg.eig(matrix)

(array([4., 2.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

-------------
# Exercise 3
Let $A$ be a $n × n$ tridiagonal matrix that results (up to an overall constant scaling factor) from an
$n$-point spatial discretization of the Laplace operator in $1$ spatial dimension. Specifically, all diagonal
elements of $A$ have the value $-2$, all elements just below or above the diagonal have value $1$.

$${\displaystyle A = \left( \begin{array}{rrrrr} -2 &  1  &  0 &  0& \ldots \\ 1  & -2 & 1 & 0 &\ldots   \\ 0 & 1 & -2 &  1 &\ldots \\ \vdots & & & & \ddots \end{array} \right) \,}$$



Take $n = 150$. Use `scipy.linalg.qr` to implement Algorithm 4.7 from the book and compute the full eigenvalue spectrum of $A$. Compare against
the eigenvalues obtained by the built-in routine `scipy.linalg.eig(A)`. Show in a figure the (approximate)
eigenvalues after 10, 100 and 500 QR iterations, as well as the eigenvalues obtained with `eig(A)`.


In [ ]:
from scipy.sparse import diags
